# Generated by Django 2.1.7 on 2019-05-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190528_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='update_at',
        ),
    ]
