# Generated by Django 2.1.7 on 2019-05-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
